name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master  # O la rama que estés usando

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub
          action: "upload"
          app_location: "./" # Directorio raíz de tu app React
          output_location: "dist" # Carpeta de salida de Vite
